name: CD

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  GODOT_VERSION: "4.7"
  EXPORT_NAME: sokoban

jobs:
  export-linux:
    name: Linux Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.7

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          lfs: true
          persist-credentials: false

      - name: Install system dependencies
        run: apt-get update && apt-get install -y build-essential curl zstd

      - name: Cache Cargo artifacts
        uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            extension/target/
          key: cargo-${{ runner.os }}-${{ github.job }}-${{ github.ref_name }}-${{ hashFiles('extension/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-${{ github.job }}-${{ github.ref_name }}-
            cargo-${{ runner.os }}-${{ github.job }}-

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build GDExtension
        run: cargo build --manifest-path extension/Cargo.toml --release

      - name: Setup Godot
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/4.7.stable ~/.local/share/godot/export_templates/4.7.stable

      - name: Export
        run: |
          mkdir -v -p build/linux
          EXPORT_DIR="$(readlink -f build)"
          godot --headless --verbose --export-release "Linux" "$EXPORT_DIR/linux/$EXPORT_NAME.x86_64"

      - name: Create archive
        run: tar -caf sokoban-linux-x86_64.tar.zst -C build/linux .

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: sokoban-linux-x86_64
          path: sokoban-linux-x86_64.tar.zst

  export-windows:
    name: Windows Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.7

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          lfs: true
          persist-credentials: false

      - name: Install system dependencies
        run: apt-get update && apt-get install -y build-essential curl g++-mingw-w64-x86-64 p7zip-full

      - name: Cache Cargo artifacts
        uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            extension/target/
          key: cargo-${{ runner.os }}-${{ github.job }}-${{ github.ref_name }}-${{ hashFiles('extension/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-${{ github.job }}-${{ github.ref_name }}-
            cargo-${{ runner.os }}-${{ github.job }}-

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-gnu

      - name: Build GDExtension
        run: |
          cargo build --manifest-path extension/Cargo.toml --release --target x86_64-pc-windows-gnu
          mkdir -p extension/target/release
          cp extension/target/x86_64-pc-windows-gnu/release/extension.dll extension/target/release/extension.dll

      - name: Setup Godot
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/4.7.stable ~/.local/share/godot/export_templates/4.7.stable

      - name: Export
        run: |
          mkdir -v -p build/windows
          EXPORT_DIR="$(readlink -f build)"
          godot --headless --verbose --export-release "Windows" "$EXPORT_DIR/windows/$EXPORT_NAME.exe"

      - name: Create archive
        run: |
          cd build/windows
          7z a -tzip ../../sokoban-windows-x86_64.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: sokoban-windows-x86_64
          path: sokoban-windows-x86_64.zip

  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.7

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          lfs: true
          persist-credentials: false

      - name: Install system dependencies
        run: apt-get update && apt-get install -y build-essential curl p7zip-full python3

      - name: Cache Cargo artifacts
        uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            extension/target/
          key: cargo-${{ runner.os }}-${{ github.job }}-${{ github.ref_name }}-${{ hashFiles('extension/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-${{ github.job }}-${{ github.ref_name }}-
            cargo-${{ runner.os }}-${{ github.job }}-

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: wasm32-unknown-emscripten
          components: rust-src

      - name: Setup Emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git /opt/emsdk --depth 1
          cd /opt/emsdk
          ./emsdk install latest
          ./emsdk activate latest

      - name: Build GDExtension
        shell: bash
        run: |
          . /opt/emsdk/emsdk_env.sh
          export EMMAKEN_CFLAGS="-sWASM_EXCEPTIONS=0"
          cd extension
          cargo +nightly build -Zbuild-std --target wasm32-unknown-emscripten --release --features godot/experimental-wasm,godot/lazy-function-tables

      - name: Setup Godot
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/4.7.stable ~/.local/share/godot/export_templates/4.7.stable

      - name: Export
        run: |
          mkdir -v -p build/wasm
          EXPORT_DIR="$(readlink -f build)"
          godot --headless --verbose --export-release "Web" "$EXPORT_DIR/wasm/index.html"

      - name: Create archive
        run: |
          cd build/wasm
          7z a -tzip ../../sokoban-web.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: sokoban-web
          path: sokoban-web.zip

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        if: github.event_name != 'pull_request'
        with:
          branch: gh-pages
          folder: build/wasm

  release:
    name: Release
    needs: [export-linux, export-windows, export-web]
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8

      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            sokoban-linux-x86_64/sokoban-linux-x86_64.tar.zst
            sokoban-windows-x86_64/sokoban-windows-x86_64.zip
            sokoban-web/sokoban-web.zip
